# Generated by Django 5.0.3 on 2024-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_description_alter_phone_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='name',
        ),
        migrations.AddField(
            model_name='phone',
            name='series',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=6),
        ),
    ]
