# Generated by Django 5.0.3 on 2024-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_phone_name_phone_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='series',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
