# Generated by Django 5.0.3 on 2024-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_phone_phone_model_alter_phone_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=10),
        ),
    ]
