# Generated by Django 5.0.3 on 2024-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
