# Generated by Django 5.0.3 on 2024-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_smartwatch_series_smartwatch_strap_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='ram',
            new_name='memory',
        ),
    ]
