# Generated by Django 5.0.3 on 2024-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_ram_phone_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(default=64),
        ),
    ]
