# Generated by Django 5.0.3 on 2024-03-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_phone_color_alter_phone_memory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartWatch',
        ),
    ]
