# Generated by Django 5.0.3 on 2024-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_phone_image_alter_phone_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='series',
        ),
    ]
